name: PR Summary

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  generate_summary:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai PyGithub
    - name: Generate PR summary
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        python .github/scripts/generate_summary.py
        
    - uses: actions/upload-artifact@v4
      with:
        name: pr-summary-report
        path: pr_summary.md
