name: Update Issue Status

on:
  create:
    branches:
      - 'feature/**'

jobs:
  update_issue:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Extract issue ID
      id: extract_issue_id
      run: |
        BRANCH_NAME="${{ github.ref_name }}"
        ISSUE_ID=$(echo $BRANCH_NAME | sed -e 's/^feature\///g')
        echo "issue_id=$ISSUE_ID" >> $GITHUB_OUTPUT
        
    - name: Update issue status
      env:
          BACKLOG_API_KEY: ${{ secrets.BACKLOG_API_KEY }}  
          BACKLOG_SPACE_NAME: your-space-name
      run: |
          pip install requests
          python /.github/script/update-backlog.py
